// <auto-generated />
namespace BrasaoSolution.Repository.Migrations.Brasao
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CriaTabelasProgramaFidelidade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriaTabelasProgramaFidelidade));
        
        string IMigrationMetadata.Id
        {
            get { return "201711091832383_CriaTabelasProgramaFidelidade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
