// <auto-generated />
namespace BrasaoSolution.Repository.Migrations.Brasao
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RetiraObrigatoriedadeFundos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RetiraObrigatoriedadeFundos));
        
        string IMigrationMetadata.Id
        {
            get { return "201805141244565_RetiraObrigatoriedadeFundos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
