//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrasaoSolution.TronSolutionData.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASSE_ITEMCARDAPIO
    {
        public CLASSE_ITEMCARDAPIO()
        {
            this.ITEM_CARDAPIO = new HashSet<ITEM_CARDAPIO>();
        }
    
        public int CD_CLASSEITEMCARDAPIO { get; set; }
        public string DS_CLASSEITEMCARDAPIO { get; set; }
        public Nullable<int> CD_EMPRESA { get; set; }
    
        public virtual ICollection<ITEM_CARDAPIO> ITEM_CARDAPIO { get; set; }
    }
}
