//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrasaoHamburgueria.TronSolutionData.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_CARDAPIO
    {
        public ITEM_CARDAPIO()
        {
            this.ITEM_CARDAPIOXEMPRESA = new HashSet<ITEM_CARDAPIOXEMPRESA>();
        }
    
        public int CD_ITEMCARDAPIO { get; set; }
        public Nullable<int> CD_IMPRESSORAPEDIDOS { get; set; }
        public Nullable<int> CD_EMPRESA { get; set; }
        public Nullable<int> CD_SITUACAOTRIBUTARIA { get; set; }
        public Nullable<int> CD_UNIDADE { get; set; }
        public Nullable<int> CD_CLASSEITEMCARDAPIO { get; set; }
        public string DS_ITEMCARDAPIO { get; set; }
        public Nullable<decimal> VALOR_VENDA { get; set; }
        public string CODIGO_BARRAS { get; set; }
        public Nullable<short> IMPRIME_NO_CARDAPIO { get; set; }
        public Nullable<short> ENVIA_COZINHA { get; set; }
        public Nullable<decimal> QTD_ESTOQUE_MINIMO { get; set; }
        public Nullable<decimal> VALOR_CUSTO_MEDIO { get; set; }
        public Nullable<decimal> VALOR_COMPRA { get; set; }
        public Nullable<short> CONTROLA_ESTOQUE { get; set; }
        public string DS_COMPOSICAO_CARDAPIO { get; set; }
        public Nullable<short> ATIVO { get; set; }
        public Nullable<int> PONTOS_FIDELIDADE { get; set; }
        public Nullable<int> CREDITOS_PROMOTER { get; set; }
        public Nullable<short> EH_COMBO { get; set; }
        public Nullable<short> PODE_PARTICIPAR_COMBO { get; set; }
        public Nullable<int> CD_UNIDADECOMPRA { get; set; }
        public Nullable<float> CONVERSAO_UNIDADECOMPRA { get; set; }
        public Nullable<short> DEVE_PESAR { get; set; }
        public Nullable<int> QTD_MAX_USUAL { get; set; }
        public Nullable<int> NR_ICONE_TOQUETELA { get; set; }
        public Nullable<int> POSICAO_TOQUETELA { get; set; }
        public Nullable<short> PODE_TELE_ENTREGA { get; set; }
        public Nullable<short> PERMITE_OBS_PRODUCAO { get; set; }
        public Nullable<short> PERMITE_ALT_INGREDIENTE { get; set; }
        public Nullable<decimal> REDUCAO_ICMS { get; set; }
        public Nullable<decimal> SUBST_ICMS { get; set; }
        public Nullable<short> PRODUCAO_PROPRIA { get; set; }
        public Nullable<short> ARREDONDA_TRUNCA { get; set; }
        public string NCM { get; set; }
        public string MD5 { get; set; }
        public string CD_GENERO_NCM { get; set; }
        public Nullable<int> EX { get; set; }
        public string CEST { get; set; }
    
        public virtual CLASSE_ITEMCARDAPIO CLASSE_ITEMCARDAPIO { get; set; }
        public virtual ICollection<ITEM_CARDAPIOXEMPRESA> ITEM_CARDAPIOXEMPRESA { get; set; }
    }
}
