//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrasaoHamburgueria.TronSolutionData.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_CARDAPIOXEMPRESA
    {
        public int CD_ITEMCARDAPIO { get; set; }
        public int CD_EMPRESA { get; set; }
        public Nullable<short> ATIVO { get; set; }
        public Nullable<int> CD_SITUACAOTRIBUTARIA { get; set; }
        public Nullable<decimal> VALOR_VENDA { get; set; }
        public Nullable<short> IMPRIME_NO_CARDAPIO { get; set; }
        public Nullable<decimal> VALOR_CUSTO_MEDIO { get; set; }
        public Nullable<decimal> VALOR_COMPRA { get; set; }
        public Nullable<int> NR_ICONE_TOQUETELA { get; set; }
        public Nullable<int> POSICAO_TOQUETELA { get; set; }
        public Nullable<decimal> REDUCAO_ICMS { get; set; }
        public Nullable<decimal> SUBST_ICMS { get; set; }
        public Nullable<int> CD_IMPRESSORAPEDIDOS { get; set; }
        public Nullable<short> ENVIA_COZINHA { get; set; }
        public Nullable<int> CD_IMPRESSORAPEDIDOS2 { get; set; }
        public Nullable<int> CD_CLASSIFICACAOFISCAL { get; set; }
        public Nullable<decimal> ALIQUOTA_ICMS { get; set; }
        public Nullable<decimal> ALIQUOTA_IPI { get; set; }
        public Nullable<int> MINUTOS_PRODUCAO { get; set; }
        public Nullable<int> MINUTOS_ALERTA_PRODUCAO { get; set; }
        public Nullable<int> MEI_TIPO_RECEITA { get; set; }
    
        public virtual ITEM_CARDAPIO ITEM_CARDAPIO { get; set; }
    }
}
