//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrasaoHamburgueria.TronSolutionData.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TronSolutionConnection : DbContext
    {
        public TronSolutionConnection()
            : base("name=TronSolutionConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLASSE_ITEMCARDAPIO> CLASSE_ITEMCARDAPIO { get; set; }
        public DbSet<ITEM_CARDAPIO> ITEM_CARDAPIO { get; set; }
        public DbSet<ITEM_CARDAPIOXEMPRESA> ITEM_CARDAPIOXEMPRESA { get; set; }
    }
}
