// <auto-generated />
namespace BrasaoHamburgueria.Web.Migrations.Identity
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CodEmpresaPadrao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CodEmpresaPadrao));
        
        string IMigrationMetadata.Id
        {
            get { return "201804301818561_CodEmpresaPadrao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
