// <auto-generated />
namespace BrasaoHamburgueria.Web.Migrations.Brasao
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ImpressoraPadraoClasse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImpressoraPadraoClasse));
        
        string IMigrationMetadata.Id
        {
            get { return "201710201616251_ImpressoraPadraoClasse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
